services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: wh_calc
      POSTGRES_PASSWORD: wh_calc
      POSTGRES_DB: wh_calc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
