packages:
  - "apps/*"
  - "packages/*"

catalog:
  clsx: 2.1.1
  prettier: 3.8.2
  typescript: 6.0.2

catalogs:
  react:
    "@tabler/icons-react": 3.41.1
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
    react: 19.2.4
    react-dom: 19.2.4

  lint:
    "@eslint/js": 10.0.1
    "@vitest/eslint-plugin": 1.6.17
    eslint: 10.2.0
    eslint-config-prettier: 10.1.8
    eslint-plugin-prefer-arrow: 1.2.3
    typescript-eslint: 8.58.1

  test:
    "@types/jest": 29.5.14
    msw: 2.11.6
    ts-jest: 29.2.5
    vitest: 4.1.4
