service: cogitator-tactica-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    NODE_ENV: production

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node20
    platform: node
    packager: pnpm
    plugins: esbuild-plugins.cjs
    external:
      - "@nestjs/microservices"
      - "@nestjs/websockets"
      - "cache-manager"
      - "class-transformer"
      - "class-validator"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
