service: cogitator-tactica-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    NODE_ENV: production
    PRISMA_QUERY_ENGINE_LIBRARY: /var/task/prisma-engines/libquery_engine-rhel-openssl-3.0.x.so.node

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node20
    platform: node
    packager: npm
    plugins: esbuild-plugins.cjs
    copyFiles:
      - from: "prisma-engines/libquery_engine-rhel-openssl-3.0.x.so.node"
        to: "prisma-engines/libquery_engine-rhel-openssl-3.0.x.so.node"
    external:
      - "@nestjs/microservices"
      - "@nestjs/websockets"
      - "cache-manager"
      - "class-transformer"
      - "class-validator"

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
