import type { UnitProfile } from "../../src/lib/calculator/types";

export const generateUnitsFile = (units: UnitProfile[]): string => {
  const unitsRecord = Object.fromEntries(units.map((u) => [u.id, u]));
  const body = JSON.stringify(unitsRecord, null, 2);

  return [
    "// Generated by scripts/import-wahapedia. Do not edit manually.",
    'import { UnitProfile } from "@/lib/calculator/types";',
    "",
    "export const UNITS: Record<string, UnitProfile> = " + body + ";",
    "",
    "export const UNIT_LIST = Object.values(UNITS);",
    "",
  ].join("\n");
};
